src/app/App.tsx, src/app/style.ts
- reset, root color, globalstyles 추가했습니다
=> :lipstick: Style : reset, root color, globalstyles 추가

src/index.tsx
=> :truck: Modify : index.tsx 경로 수정

src/atoms/button/Button.tsx
resolves: # 
- 
- 아톰 버튼 컴포넌트 개발
- 백그라운드 색상과, 호버색상, 내부 내용, 이벤트리스너 props로 받아와 설정가능
- 
- 특이 사항
close: #
=> :sparkles: Feat: 버튼 아톰 구현

src/atoms/inputs/Inputs.tsx, src/atoms/inputs/style.ts
resolves: # 
- 마크업
- 아톰 인풋컴포넌트 개발
- ui > gradients 사용
- 포커싱되었을 시 백그라운드 색상 #fff000 변경
- 
- 특이 사항
close: #
=> :sparkles: Feat: 아톰 인풋 컴포넌트 개발

src/atoms/image/Image.tsx
resolves: # 
- 마크업
- 아톰 이미지컴포넌트 구현
- width, height, src, alt props로 받아 설정
- 특이 사항
close: #
=> :sparkles: Feat: 아톰 이미지컴포넌트 구현

src/pages/joinPage/JoinPage.tsx, src/pages/loginPage/LoginPage.tsx
resolves: # 
- 회원가입 페이지 마크업 구현
- 특이 사항
close: #
=> :sparkles: Feat: 회원가입페이지 마크업 구현

src/atoms/button/Button.tsx, src/components/quizList/QuizList.tsx, src/components/quizList/style.ts, src/pages/joinQuizPage/JoinQuizPage.tsx, src/pages/profilePage/ProfilePage.tsx
resolves: # 
- 퀴즈리스트 컴포넌트 필요로 추가
- 퀴즈리스트 컴포넌트 마크업 구현
- 퀴즈 페이지 마크업 구현
###
작업 후 기대 동작(스크린샷)
close: #
=> :sparkles: Feat: 퀴즈 리스트 컴포넌트, 퀴즈 페이지 마크업 구현

src/atoms/button/closeBtn/CloseBtn.tsx, src/atoms/button/closeBtn/style.ts
resolves: # 
- 
- 모달에 들어가는 취소 (x) 버튼을 생성했습니다. 
- 
- 특이 사항
close: #20
=> :sparkles: Feat : 취소 버튼 생성

src/atoms/icon/Icon.tsx, src/components/catFeed/CatFeed.tsx, src/components/catFeed/feedCard/FeedCard.tsx, src/components/catFeed/feedCard/style.ts, src/components/catFeed/style.ts, src/components/catInfo/CatInfo.tsx, src/pages/catInfoPage/CatInfoPage.tsx
resolves: #30 
- 냥이 정보 상세 페이지에 들어가는 컴포넌트 개발 
- 
- 아톰 폴더에 아이콘 폴더가 있어서 이미지로 사용할지 아이콘에 넣어서 사용할지 고민하다 넣었는데..안되면 빼겠습니다!! 
close: #30
=> ✨Feat : 냥이 정보 상세 페이지 마크업 구현 

src/components/modal/termsModal/TermsModal.tsx, src/components/modal/termsModal/style.ts
resolves: # 
-  이용 약관 모달을 생성했습니다. 
- 
- 특이 사항
close: #34
=> :sparkles: Feat : 이용약관 모달 생성

src/components/modal/deleteModal/DeleteModal.tsx, src/components/modal/deleteModal/style.ts
resolves: # 
- 코드에 오류가 있어서 수정했습니다.
- 스타일 컴포넌트를 다 넣지 않고 커밋해서 수정했습니다.
- 
- 특이 사항
close: #38
=> :lipstick: Modify : 삭제 모달 에러 코드 수정

src/pages/splashPage/Splash.tsx, src/pages/splashPage/style.ts
resolves: # 
- 
-  스플래시 페이지 마크업 구현
- 
- 특이 사항
close: #
=> :sparkles: Feat: 스플래시 페이지 마크업 구현

src/components/menuBoard/MenuBoard.tsx, src/components/modal/mapModal/MapModal.tsx, src/components/searchInpBox/SearchInpBox.tsx
resolves: #41 
- 양옆 패딩값 수정 필요
- 양옆 패딩값 40px로 수정
- 없음
close: #41
=> :lipstick: Modify : 양옆 padding 값 40px로 수정 #41

src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/components/modal/catFoodPageModal/style.ts, src/components/modal/style.ts
resolves: # 
- 밥주기 모달 마크업 했습니다.
- 피그마와 비슷하게 만들어 놨습니다.
- 아직 select 박스랑 버튼 클릭시 이미지 변경은 하지 못했습니다.
- 
- 특이 사항
close: #36
=> :sparkles: Feat : 밥주기 모달 마크업 생성

src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/components/modal/catFoodPageModal/style.ts
resolves: # 
- 시간 설정 부분의 select 박스를 제거하고 input창으로 변경했습니다.
- 현재 시간 버튼도 추가했습니다.
- 
close: #46
=> :sparkles: Feat : select박스 제거 후 input 생성, 현재시간 버튼 생성

src/components/menuBoard/MenuBoard.tsx, src/components/menuBoard/style.ts, src/components/modal/Modal.tsx, src/components/modal/mapModal/MapModal.tsx, src/components/modal/mapModal/style.ts, src/components/searchInpBox/SearchInpBox.tsx, src/components/searchInpBox/style.ts, src/components/sideBar/SideBar.tsx, src/components/sideBar/style.ts
resolves: #48 
- style.ts 로 파일분기
- 없음
close: #48
=> :lipstick: Modify : style.ts 파일 분기

src/atoms/button/closeBtn/CloseBtn.tsx, src/components/catInfo/CatInfo.tsx, src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/components/modal/catModal/CatModal.tsx, src/components/modal/deleteModal/DeleteModal.tsx, src/components/modal/deleteModal/style.ts, src/components/modal/termsModal/TermsModal.tsx
resolves: # 
- 모달 연결
- 고양이 상세 페이지에 정보 삭제 모달을 연결했습니다.
- 
- 특이 사항
close: #54
=> :sparkles: Feat : 고양이 정보 삭제 모달 연결

src/components/catFeed/feedCard/FeedCard.tsx
resolves: # 
- 모달 연결 
- 고양이 밥 정보 삭제 모달 연결
- 
- 특이 사항
close: #56
=> :sparkles: Feat : 고양이 밥 정보 삭제 모달 연결

src/components/menuBoard/MenuBoard.tsx, src/components/menuBoard/style.ts, src/components/searchInpBox/SearchInpBox.tsx, src/components/searchInpBox/style.ts, src/pages/recordMapPage/RecordMapPage.tsx
resolves: #59 
- 메뉴 버튼 클릭 시 게시판 모달 열기
- 아직 고쳐야 할 부분이 많아효,,,🥲
close: #59
=> :sparkles: Feat : 메뉴 버튼 클릭시 게시판 모달 열기

src/components/menuBoard/MenuBoard.tsx, src/components/menuBoard/style.ts, src/pages/recordMapPage/RecordMapPage.tsx, src/pages/recordMapPage/style.ts
resolves: #65 
- 기존 코드에 useState 새로 선언되어 적용되지 않음
- useState 선언되어 있는 파일에서 코드 재작성
- 없음
close: #65
=> :sparkles: Modify : 게시판 모달창 수정

src/pages/catInfoPage/CatInfoPage.tsx
resolves: #69 
- 모달 연결
-  밥주기 모달 연결
close: #69
=> :sparkles: Feat : 고양이 상세 페이지에 밥주기 모달 연결

.prettierrc, package-lock.json, package.json, public/index.html, src/pages/recordMapPage/MyLocation.tsx, src/pages/recordMapPage/RecordMapPage.tsx, src/pages/recordMapPage/style.ts, tsconfig.json
resolves: #76 
- 카카오맵 API 연결
- 홈 화면 현위치 표시 
- 잘 동작하나요 🤔 ㄱ-
close: #76
=> :sparkles: Feat : 카카오맵 API 연결 및 홈 화면에 현위치 표시하기

src/atoms/image/Image.tsx, src/components/header/Header.tsx, src/components/header/style.ts, src/pages/registerCatPage/RegisterCatPage.tsx, src/pages/registerCatPage/style.ts
resolves: #79
- 로컬 사진 등록
- 헤더 뒤로가기 추가
- 이미지 컴포넌트 클릭이벤트 추가 
close: #79
=> ✨ Feat: 로컬 고양이사진등록 및 헤더,이미지 컴포넌트 기능추가 

package-lock.json
- package-lock.json 컨플릭트 해결 후 푸쉬
=> :bug: Modify: package-lock.json conflict 해결

package-lock.json
- package-lock.json 컨플릭트 해결 후 푸쉬
=> :bug: Modify: package-lock.json conflict 해결 추가

src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/components/modal/catFoodPageModal/style.ts
resolves: #71 
- 밥주기 페이지에서 밥, 간식, 물 버튼 클릭시 이미지 변화
- 이미지 변화
- 버튼 포커스는 아직 못함,,,
- 
close: #71
=> :sparkles: Feat : 고양이 밥 버튼들 클릭시 이미지 변화

src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/components/modal/catFoodPageModal/style.ts
resolves: #85 
- 이미지 클릭시 버튼의 배경색 변경
- 밥주기 페이지에서 밥, 간식, 물 이미지 클릭시 글의 배경색이 변하게 했습니다.
- 
- 특이 사항
close: #85
=> :lipstick: Modify : 밥주기 페이지에서 이미지 클릭시 배경색 변경

src/pages/errorPage/ErrorPage.tsx
resolves: #
- 
- 404 페이지에서 버튼 클릭시 이전 페이지로 이동하는 기능 구현
https://user-images.githubusercontent.com/102498600/197935477-995fe5f4-e23a-49e6-93d0-86228853eedd.mp4
- 특이 사항
close: #
=> :sparkles: Feat : 404 페이지 기능 구현

src/atoms/button/Button.tsx, src/atoms/dropdown/DropDown.tsx, src/atoms/dropdown/style.ts, src/components/header/Header.tsx, src/pages/registerCatPage/RegisterCatPage.tsx, src/pages/registerCatPage/style.ts
resolves: #87  
- 클릭시 재렌더링 해결
- 클릭시 밑에 내용 밀림 해결
- 클릭요소 선택 
화살표 아이콘 아직 해결 중
close: #87
=> ✨ Add 드롭다운 요소 선택 및 밀림 해결 

src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/components/modal/catFoodPageModal/style.ts
resolves: #92 
- 현재시간 버튼 클릭시 현재시간이 나타납니다.
- 하지만 시간이 버튼 클릭시 마다 변하지 않고, 다른 글을 작성하면 반영이 되고 있지 않아 수정이 필요합니다.
- 버튼 클릭시 현재 시간 나옴.
- 
- 특이 사항
close: #92
=> :sparkles: Feat : 현재시간 기능 구현

src/components/mapTemplate/MapTemplate.tsx, src/components/mapTemplate/style.ts, src/components/searchInpBox/SearchInpBox.tsx, src/components/searchInpBox/style.ts, src/pages/recordMapPage/RecordMapPage.tsx, src/pages/recordMapPage/style.ts
resolves: #94 
- 장소, 주소 검색기능 구현
- 키워드 또는 주소지로 검색 가능
- 없음
close: #94
=> :sparkles: Feat : 지도 검색기능 구현

src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/components/modal/catFoodPageModal/style.ts
resolves: #96 
- 현재 시간 버튼 삭제
- 시간 설정 수정
- 페이지를 열면 바로 현재 시간이 input에 나타나도록 했습니다.
- input type="time"으로 input을 변경했습니다.
close: #96
=> :sparkles: Feat : 시간 설정 수정, 현재시간 버튼 삭제

src/atoms/dropdown/style.ts, src/pages/registerCatPage/RegisterCatPage.tsx, src/pages/registerCatPage/style.ts
resolves: #98
- 냥이 등록 페이지 주소창 마크업 
- 
- 특이 사항
close: #98
=> 💄Style: 냥이등록페이지 주소창추가

src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
resolves: #100 
- 
- 밥주기페이지에 감귤마켓 댓글 api를 연결했습니다.
- post만 가능하고 임시 토큰과 임시로 postId를 적어서 완성했습니다.
- 
close: #100
=> :sparkles: Feat : 밥주기 페이지에 감귤마켓 댓글 api연결

src/components/catFeed/CatFeed.tsx, src/components/catFeed/feedCard/FeedCard.tsx, src/pages/catInfoPage/CatInfoPage.tsx
resolves: #103
- 
- api 연동하여 post로 정보를 불러왔습니다.
- 불러온 정보를 split를 사용하여 다시 보여주었습니다.
- 특이 사항
close: #103
=> :sparkles: Feat : 고양이 밥 정보 리스트를 상세페이지에 보여주기

src/components/modal/mapModal/MapModal.tsx, src/pages/recordMapPage/RecordMapPage.tsx, src/pages/registerCatPage/RegisterCatPage.tsx
resolves: #105 
- 냥이 등록 페이지에 지도에서 선택한 주소, 입력한 상세주소 넘겨주기
- 없음
close: #105
=> :sparkles: Feat : 냥이 등록 페이지에 입력한 주소 넘겨주기

src/components/catFeed/CatFeed.tsx, src/components/catFeed/feedCard/FeedCard.tsx
resolves:#107
- 밥주기 스크롤 생성 
- 카드 3개만 보여주는 로직으로 구현하려고 했으나.
- 다 보여주는 스크롤로 변경
=> :lipstick: Style: 밥주기 스크롤 구현

src/atoms/button/Button.tsx, src/atoms/dropdown/DropDown.tsx, src/pages/registerCatPage/RegisterCatPage.tsx, src/pages/registerCatPage/style.ts
resolves: #102 
- 냥이 api등록 후 페이지 이동
- 스타일 수정( 냥이 정보페이지 사진)
- 드롭다운 프롭스 전달 
close: #102 
- 밸리데이션 추가 후 페이지 이동
- 냥이 정보 페이지에 데이터 뿌리기
=> ✨ Feat: 냥등록api 등록 후 페이지 이동 및 스타일 수정

src/components/catFeed/feedCard/FeedCard.tsx, src/components/catInfo/CatInfo.tsx, src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/components/modal/deleteModal/DeleteModal.tsx, src/pages/catInfoPage/CatInfoPage.tsx
resolves: #110
- 삭제 api 연결
- 
- 
- 특이 사항
close: #110
=> :sparkles: Feat : 밥 정보에 삭제 api 연결

src/components/catFeed/feedCard/FeedCard.tsx, src/components/modal/catFoodPageModal/CatFoodPageModal.tsx
resolves: #114 
- 괄호 위치 변경
- 
close: #114
=> :lipstick: Modify : 괄호 위치 변경

src/app/App.tsx, src/atoms/inputs/Inputs.tsx, src/components/catInfo/CatInfo.tsx, src/components/catInfo/style.ts, src/pages/registerCatPage/RegisterCatPage.tsx
resolves: #116  
- 유효성 검사 및 데이터 뿌리기 
- 냥이 이름, 사진, 주소 (필수) 
- 냥이 출생,특이사항 (필수 x )
- 특이 사항
close: #116 
- 엑박 조심...
=> ✨ Feat: 냥이 유효성 검사 및 냥이 상세페이지에 데이터 뿌리기 

src/components/catFeed/CatFeed.tsx, src/components/catFeed/feedCard/FeedCard.tsx, src/components/header/Header.tsx
resolves: #118 
- 
- 작성한 밥 정보를 날짜로 분류하려고 함.
- 아직 정보를 날짜별로 분류는 못했고 날짜만 따로 나오게만 한 상태
- 
- 특이 사항
close: #118
=> :sparkles: Feat : 밥정보 날짜별 분류

src/components/catInfo/CatInfo.tsx, src/components/catInfo/style.ts, src/pages/catInfoPage/CatInfoPage.tsx, src/pages/registerCatPage/RegisterCatPage.tsx, src/styles/commonStyle.ts
resolves: #120 
- 이미지 엑박 ../ 추가 
close: #120
=> ✨ Modify: 엑박해결

src/components/catFeed/CatFeed.tsx, src/components/catFeed/feedCard/FeedCard.tsx, src/components/catFeed/feedCard/style.ts, src/components/catFeed/style.ts, src/components/catInfo/CatInfo.tsx, src/components/catInfo/style.ts, src/pages/catInfoPage/style.ts, src/pages/registerCatPage/RegisterCatPage.tsx
resolves: #122 
- 게시물 api 변경 
- post.id 받기 위해!
close: #122
=> ✨ Feat/냥이등록게시물api로변경

src/components/catFeed/CatFeed.tsx
resolves: #124 
- 
- 오늘 날짜의 밥 정보만 나오게 함
- 
- 특이 사항
close: #124
=> :lipstick: Modify : 밥 날짜 정보 수정, 오늘 날짜의 정보만 나오게 함

src/components/catFeed/CatFeed.tsx, src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/components/modal/deleteModal/DeleteModal.tsx, src/pages/catInfoPage/CatInfoPage.tsx
resolves: #126 
- postId를 연결함.
- 게시글 마다 댓글과 삭제가 가능
- 
- 
- 특이 사항
close: #126
=> Modify : api 수정

src/components/modal/deleteModal/DeleteModal.tsx
resolves: #129 
- 삭제 api 등록 후 홈으로 이동 
close: #129
=> :sparkles: 삭제 api 등록

src/atoms/button/Button.tsx, src/atoms/inputs/Inputs.tsx, src/hooks/useInput.tsx, src/pages/joinPage/JoinPage.tsx, src/pages/joinQuizPage/JoinQuizPage.tsx, src/pages/loginPage/LoginPage.tsx, src/pages/loginPage/style.ts, src/pages/profilePage/ProfilePage.tsx
resolves: #63
- 
- 특이 사항
close: #63
=> ✨ Feat: 로그인 기능구현(api 연결, 유저 정보 로컬스토리지 저장)

src/pages/splashPage/Splash.tsx
resolves: #132 
- 
- 스플래시 페이지에서 로고가 사라지는 애니메이션과 로그인 페이지로 이동하는 기능을 구현했습니다.
https://user-images.githubusercontent.com/102498600/201675841-d1465cb1-86df-42f5-aa45-812bc0290caf.mp4
close: #132
=> :sparkles: Feat : 스플래시 페이지 기능 구현

src/atoms/button/Button.tsx, src/pages/catInfoPage/CatInfoPage.tsx, src/pages/registerCatPage/RegisterCatPage.tsx
resolves: #134 
- 등록하기 버튼 시 에러 
- 버튼 수정 props 추가 
close: #134
=> :bug: Modify: 버튼 props 추가

src/components/catFeedNone/CatFeedNone.tsx, src/components/catFeedNone/style.ts, src/pages/catInfoPage/CatInfoPage.tsx
resolves: #138 
- 페이지 생성
- 
- <img width="143" alt="image" src="https://user-images.githubusercontent.com/84389307/201717664-4f4574ba-153a-4ea3-8006-503b7fbd57a2.png">
- 특이 사항
close: #138
=> :sparkles: Feat : 밥정보 없을 때 꼬르륵 페이지가 나오도록 만듬

src/pages/catInfoPage/CatInfoPage.tsx
resolves: #140 
- 
- 꼬르륵 페이지 다시 올리기
- 
- 특이 사항
close: #140
=> :lipstick: Modify : 꼬르륵 페이지 다시 올리기

src/components/catFeed/CatFeed.tsx, src/components/catFeed/feedCard/FeedCard.tsx
resolves: #128
- 본인이 작성한 밥 정보만 삭제가 가능합니다. 
- 
- 특이 사항
close: #128
=> :sparkles: Feat : 본인이 작성한 밥 정보만 삭제 가능

src/Route.tsx, src/components/catInfo/CatInfo.tsx, src/components/catList/CatList.tsx, src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/pages/loginPage/LoginPage.tsx, src/pages/registerCatPage/RegisterCatPage.tsx
resolves: #148 
- 로그인 시 로컬스토리지에 토큰정보를 넣어주고 있기 때문에 임시토큰이 필요없어서 제거합니다.
- 임시토큰 제거
close: #148
=> :lipstick: Modify : 임시 토큰 제거

src/app/App.tsx, src/components/catNewsItem/CatNewItem.tsx, src/pages/catNewsPage/CatNewsPage.tsx
resolves: #150
- 
- 밥줬냥 신문 마크업을 했습니다.
- 
- 특이 사항
close: #150
=> :sparkles: Feat : 밥줬냥 신문 마크업

src/app/App.tsx, src/atoms/dropdown/DropDown.tsx, src/components/catInfo/CatInfo.tsx, src/pages/catInfoEditPage/CatinfoEditPage.tsx, src/pages/registerCatPage/RegisterCatPage.tsx, src/pages/registerCatPage/style.ts
resolves: #152 
- 냥이 정보에서 수정 클릭 시 
이름, 주소, 출생, 특이사항 state로 받아와서 뿌리기 
- api 서버 등록 후 상세페이지로 나가기
- any, 콘솔 수정 예정 
close: #152
=> :sparkles: Add: 수정기능 추가

src/components/header/Header.tsx, src/components/header/style.ts, src/components/mapTemplate/style.ts, src/pages/catNewsPage/CatNewsPage.tsx
resolves: #158 
- 헤더 컴포넌트 홈 버튼 스타일 수정
close: #158
=> :lipstick: Modify : 헤더 컴포넌트 홈 버튼 수정

src/components/catList/CatList.tsx, src/components/modal/catInfoModal/CatInfoModal.tsx, src/components/modal/catInfoModal/style.ts, src/pages/catLetterPage/CatLetterPage.tsx, src/pages/recordMapPage/RecordMapPage.tsx, src/pages/recordMapPage/style.ts
resolves: #162 
- 등록한 냥이 지도에 마커찍기
- 등록된 마커에 냥이 모달 연결하기 
- 없음
close: #162
=> :sparkles: Feat : 등록한 냥이들 마커 찍기 & 마커에 냥이 모달 등록하기

src/pages/catInfoPage/CatInfoPage.tsx
resolves: #164
- 
- 수정 완!
- 
- 특이 사항
close: #164
=> :lipstick: Modify : 오늘 등록한 밥 정보가 없을 경우 수정

src/components/catList/CatList.tsx, src/components/mapTemplate/MapTemplate.tsx, src/components/mapTemplate/style.ts, src/components/modal/catInfoModal/CatInfoModal.tsx, src/components/searchInpBox/SearchInpBox.tsx, src/components/searchInpBox/style.ts, src/pages/recordMapPage/RecordMapPage.tsx
resolves: #166 
- 일치하는 냥이 정보 모달에 입력 
- 특이 사항
close: #166
=> :sparkles: Modify : 냥이 모달 정보 수정

src/components/catInfo/style.ts, src/pages/registerCatPage/RegisterCatPage.tsx
resolves: #168 
- [x ] 기능 수정 :
- 보더래디어스 수정 및 코드정리
close: #168
=> :lipstick: Modify: 보더래디어스 수정 및 코드정리

src/pages/loginPage/LoginPage.tsx
resolves: # 
- 로그인 인풋창에 초기값이 객체로 나와서 변경
- useInput의 초기값을 {} => string으로 변경
- 
- 특이 사항
close: #
=> :bug: Modify: 로그인 인풋창 초기값 설정 변경

src/pages/registerCatPage/RegisterCatPage.tsx
resolves: #178 
- 냥이 정보 수정시 초깃값으로 나옴 
- 냥이 정보 수정시 그대로 등록된 값으로 나오게 변경 
close: #178
=> :bug: Modify:냥이 수정 출생년도

src/components/joinQuizPage/JoinQuizPage.tsx, src/components/modal/termsModal/TermsModal.tsx
resolves: # 
- 
- 
- 
- 특이 사항
close: #
=> :lipstick: Modify: 퀴즈페이지 약관모달 설정

src/components/catLettersItem/style.ts, src/components/mapTemplate/style.ts, src/components/menuBoard/MenuBoard.tsx, src/components/menuBoard/style.ts, src/components/modal/deleteModal/style.ts, src/components/modal/mapModal/style.ts, src/components/modal/style.ts, src/components/searchInpBox/style.ts, src/components/tutorialButton/TutorialBtn.tsx, src/components/tutorialButton/style.ts, src/pages/catLetterPage/CatLetterPage.tsx, src/pages/catLetterPage/style.ts, src/pages/catListPage/style.ts, src/pages/recordMapPage/RecordMapPage.tsx, src/pages/recordMapPage/style.ts, src/styles/commonStyle.ts
resolves: # 
- 전체 스타일 수정
- 
- 특이 사항
close: #
=> :lipstick: Modify : 전체 스타일 수정

src/atoms/dropdown/style.ts, src/components/catFeed/CatFeed.tsx, src/components/catFeed/feedCard/FeedCard.tsx, src/components/catInfo/CatInfo.tsx, src/components/home/Home.tsx, src/components/home/style.ts, src/components/joinQuizPage/JoinQuizPage.tsx, src/components/letterBox/LetterBox.tsx, src/components/letterBox/style.ts, src/components/loading/style.ts, src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/components/modal/catFoodPageModal/style.ts, src/components/modal/catModal/CatModal.tsx, src/components/modal/deleteModal/DeleteModal.tsx, src/components/modal/deleteModal/style.ts, src/components/modal/termsModal/TermsModal.tsx, src/components/modal/termsModal/style.ts, src/pages/catInfoEditPage/style.ts, src/pages/catInfoPage/CatInfoPage.tsx, src/pages/catListPage/CatListPage.tsx, src/pages/registerCatPage/RegisterCatPage.tsx
resolves: # 
- UI 수정 및 콘솔, 주석 제거 
- 특이 사항
close: #
=> :lipstick: Modify : UI 수정

src/components/catFeed/CatFeed.tsx
resolves: # 
- [에러메세지] Warning: Each child in an array or iterator should have a unique “key” prop.
고유 key값이 있는데 에러가 떠서 확인해보니 최상위 태그에 key값을 부여하지 않음 -> 수정
- 삼항연산자 간결하게 변경
- 상위 태그 시멘틱 태그<article>로 변경
close: #
(콘솔 삭제하고 머지 하겠슴당 머지하지 말아주세요 힣)
=> :bug: Modify: unique key 에러 해결 및 삼항연산자, 태그명 변경

src/components/tutorial/Tutorial.tsx, src/components/tutorial/appTutorial/AppTutorial.tsx, src/components/tutorialButton/TutorialBtn.tsx, src/pages/catListPage/CatListPage.tsx, src/pages/recordMapPage/RecordMapPage.tsx, src/styles/commonStyle.ts
=> :art: Modify : 이미지 alt 값 생성

src/pages/loginPage/style.ts, src/pages/registerCatPage/RegisterCatPage.tsx, src/pages/registerCatPage/style.ts
resolves: #192 
-  냥이 정보 특이사항 placeholder 보이기 
- 로그인 페이지 z-index 추가 
- 냥이 이미지 아이콘 경로 수정 
close: #192
=> 🐛  냥이 정보 특이사항 placeholder , 스타일 수정 

src/components/catFeed/CatFeed.tsx, src/pages/catInfoPage/CatInfoPage.tsx
resolves: #194 
- 오류 수정
- 수정을 이미 했었지만 다른곳도 함께 수정하지 않아서 제대로 나오고 있지 않았다..
- 다시 오늘 등록했지만 createdAt 때문에 오늘이 아닌 어제로 날짜가 저장되고 있던 오류를 수정하였고 원래대로 나오게 함..
- 
- 특이 사항
close: #194
=> :lipstick: Modify : 밥정보 리스트 오류 수정

src/components/modal/catInfoModal/style.ts, src/pages/catListPage/style.ts
resolves: #196 
- 이미지 css 수정
- 특이 사항
close: #196
=> :lipstick: Modify : 이미지 css 수정

src/components/catInfo/style.ts, src/pages/catInfoPage/CatInfoPage.tsx, src/pages/catInfoPage/style.ts
resolves: #199
- 고양이 상세정보 내용이 길어지면 버튼이 밀려남
- 고양이 상세정보 내용이 짧으면 여백 비중이 큼
- 밥주기 버튼 위치 고정
- 고양이 특이사항 부분 고정 높이값 제거
close: #199
=> :lipstick: Style: 고양이 상세페이지 UI 변경

src/components/catInfo/style.ts, src/components/modal/catInfoModal/CatInfoModal.tsx, src/components/modal/catInfoModal/style.ts, src/components/modal/mapModal/MapModal.tsx, src/pages/catListPage/style.ts, src/pages/recordMapPage/RecordMapPage.tsx, src/pages/registerCatPage/RegisterCatPage.tsx
resolves: #201 
- 모달 닫기 버튼 수정 
- 주소 인풋창 글자제한 추가
- 특이 사항
close: #201
=> :bug: Modify : 모달 닫기 버튼 수정 & 주소 인풋창 글자제한 추가

src/components/catInfo/CatInfo.tsx, src/pages/registerCatPage/RegisterCatPage.tsx
resolves: #203 
-  [x]  특이사항에 placeholder홀더가 보여야함
close: #203
=> :bug: Modify: 냥이 정보 수정시 특이사항 적용안됨

src/atoms/button/Button.tsx, src/atoms/button/style.ts, src/atoms/dropdown/DropDown.tsx, src/atoms/image/Image.tsx, src/atoms/image/style.ts, src/atoms/inputs/Inputs.tsx, src/atoms/inputs/style.ts, src/components/catFeedNone/CatFeedNone.tsx, src/components/catFeedNone/style.ts, src/components/catNewsItem/CatNewItem.tsx, src/components/catNewsItem/style.ts, src/components/joinQuizPage/style.ts, src/pages/catInfoPage/style.ts, src/pages/catNewsPage/CatNewsPage.tsx, src/pages/catNewsPage/style.ts, src/pages/errorPage/ErrorPage.tsx, src/pages/errorPage/style.ts, src/pages/joinPage/style.ts, src/pages/profileEditPage/ProfileEditPage.tsx, src/pages/profilePage/ProfilePage.tsx, src/pages/splashPage/Splash.tsx, src/pages/splashPage/style.ts
resolves: #205 
- style.ts 파일 분기
- 
- 특이 사항
close: #205
=> :art: Modify : style.ts 파일 분기

src/components/catFeed/CatFeed.tsx, src/components/modal/catFoodPageModal/CatFoodPageModal.tsx, src/components/modal/catFoodPageModal/style.ts
resolves: #207 
- 
- 밥등록시 밥종류 버튼을 클릭하지 않으면 저장되지 않도록 했습니다. 
- 
- 특이 사항
close: #207
=> :lipstick: Modify : 밥등록시 밥정보가 없으면 저장할수  없음

src/components/tutorial/appTutorial/AppTutorial.tsx, src/pages/recordMapPage/RecordMapPage.tsx
resolves: #212 
- 로그인 상태에서 모바일 튜토리얼 하루만 보기
- 
- 특이 사항
close: #212
=> :sparkles: Feat : 로그인 상태에서 모바일 튜토리얼 하루만 보기
